[versions]
agp = "8.2.0-alpha15"
kotlin = "1.8.21"
compose-multiplatform = "1.5.0-beta01"
compose-compiler = "1.4.7"
core-ktx = "1.10.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.1" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.7.2" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

